// Generated by apps/mobile/scripts/sync-offline-assets.mjs.
// Do not edit by hand. Bundled route images: Discover-card hero thumbnails AND
// on-route POI thumbnails ("נקודות עניין בדרך"), required from within the app
// package (Metro won't serve images required from the @cycleways/core workspace
// package). Keyed by the original webp logical path; the bundled file is a jpg
// (RN core <Image> can't decode webp on iOS).

export const ROUTE_IMAGES = {
  "public-data/poi-images/kovshey-hagolan-hero-4403bbce-thumb.webp": require("../../assets/data/public-data/poi-images/kovshey-hagolan-hero-4403bbce-thumb.jpg"),
  "public-data/poi-images/poi-03007424-8e53f5c4-thumb.webp": require("../../assets/data/public-data/poi-images/poi-03007424-8e53f5c4-thumb.jpg"),
  "public-data/poi-images/poi-0d152fab-255f43bc-thumb.webp": require("../../assets/data/public-data/poi-images/poi-0d152fab-255f43bc-thumb.jpg"),
  "public-data/poi-images/poi-11102fea-572cdcba-thumb.webp": require("../../assets/data/public-data/poi-images/poi-11102fea-572cdcba-thumb.jpg"),
  "public-data/poi-images/poi-1821461d-91d526fa-thumb.webp": require("../../assets/data/public-data/poi-images/poi-1821461d-91d526fa-thumb.jpg"),
  "public-data/poi-images/poi-1a4c1f16-b96c2372-thumb.webp": require("../../assets/data/public-data/poi-images/poi-1a4c1f16-b96c2372-thumb.jpg"),
  "public-data/poi-images/poi-1eb44fd0-4dd46f81-thumb.webp": require("../../assets/data/public-data/poi-images/poi-1eb44fd0-4dd46f81-thumb.jpg"),
  "public-data/poi-images/poi-23d6dbf0-325f9ead-thumb.webp": require("../../assets/data/public-data/poi-images/poi-23d6dbf0-325f9ead-thumb.jpg"),
  "public-data/poi-images/poi-38b469d3-eadbb56a-thumb.webp": require("../../assets/data/public-data/poi-images/poi-38b469d3-eadbb56a-thumb.jpg"),
  "public-data/poi-images/poi-3af86b92-04323504-thumb.webp": require("../../assets/data/public-data/poi-images/poi-3af86b92-04323504-thumb.jpg"),
  "public-data/poi-images/poi-482e2483-83028d1d-thumb.webp": require("../../assets/data/public-data/poi-images/poi-482e2483-83028d1d-thumb.jpg"),
  "public-data/poi-images/poi-521bbc87-9fdd2f58-thumb.webp": require("../../assets/data/public-data/poi-images/poi-521bbc87-9fdd2f58-thumb.jpg"),
  "public-data/poi-images/poi-53d4e045-24f5d79e-thumb.webp": require("../../assets/data/public-data/poi-images/poi-53d4e045-24f5d79e-thumb.jpg"),
  "public-data/poi-images/poi-5b6da297-fd491b50-thumb.webp": require("../../assets/data/public-data/poi-images/poi-5b6da297-fd491b50-thumb.jpg"),
  "public-data/poi-images/poi-7004abaf-b3f48c12-thumb.webp": require("../../assets/data/public-data/poi-images/poi-7004abaf-b3f48c12-thumb.jpg"),
  "public-data/poi-images/poi-7442a920-eaed8fae-thumb.webp": require("../../assets/data/public-data/poi-images/poi-7442a920-eaed8fae-thumb.jpg"),
  "public-data/poi-images/poi-75f40178-b465e980-thumb.webp": require("../../assets/data/public-data/poi-images/poi-75f40178-b465e980-thumb.jpg"),
  "public-data/poi-images/poi-77f69a67-3c7b3936-thumb.webp": require("../../assets/data/public-data/poi-images/poi-77f69a67-3c7b3936-thumb.jpg"),
  "public-data/poi-images/poi-7f0a3972-1973492b-thumb.webp": require("../../assets/data/public-data/poi-images/poi-7f0a3972-1973492b-thumb.jpg"),
  "public-data/poi-images/poi-857aa85d-088f1532-thumb.webp": require("../../assets/data/public-data/poi-images/poi-857aa85d-088f1532-thumb.jpg"),
  "public-data/poi-images/poi-86a4607d-aeab1967-thumb.webp": require("../../assets/data/public-data/poi-images/poi-86a4607d-aeab1967-thumb.jpg"),
  "public-data/poi-images/poi-8e08b582-107f7255-thumb.webp": require("../../assets/data/public-data/poi-images/poi-8e08b582-107f7255-thumb.jpg"),
  "public-data/poi-images/poi-95010070-e9f669c1-thumb.webp": require("../../assets/data/public-data/poi-images/poi-95010070-e9f669c1-thumb.jpg"),
  "public-data/poi-images/poi-972b4305-7eba303a-thumb.webp": require("../../assets/data/public-data/poi-images/poi-972b4305-7eba303a-thumb.jpg"),
  "public-data/poi-images/poi-a76cdd1b-3f8a59d2-thumb.webp": require("../../assets/data/public-data/poi-images/poi-a76cdd1b-3f8a59d2-thumb.jpg"),
  "public-data/poi-images/poi-a96860fc-71a8e561-thumb.webp": require("../../assets/data/public-data/poi-images/poi-a96860fc-71a8e561-thumb.jpg"),
  "public-data/poi-images/poi-b0a7c0c7-d717983c-thumb.webp": require("../../assets/data/public-data/poi-images/poi-b0a7c0c7-d717983c-thumb.jpg"),
  "public-data/poi-images/poi-c6c5fae3-e663e2e7-thumb.webp": require("../../assets/data/public-data/poi-images/poi-c6c5fae3-e663e2e7-thumb.jpg"),
  "public-data/poi-images/poi-c723c695-dc902444-thumb.webp": require("../../assets/data/public-data/poi-images/poi-c723c695-dc902444-thumb.jpg"),
  "public-data/poi-images/poi-d2081ac2-000a5417-thumb.webp": require("../../assets/data/public-data/poi-images/poi-d2081ac2-000a5417-thumb.jpg"),
  "public-data/poi-images/poi-df4652b4-3f8a59d2-thumb.webp": require("../../assets/data/public-data/poi-images/poi-df4652b4-3f8a59d2-thumb.jpg"),
  "public-data/poi-images/poi-e144a450-8d7e7468-thumb.webp": require("../../assets/data/public-data/poi-images/poi-e144a450-8d7e7468-thumb.jpg"),
  "public-data/poi-images/poi-f5fd1f27-34405fc1-thumb.webp": require("../../assets/data/public-data/poi-images/poi-f5fd1f27-34405fc1-thumb.jpg"),
  "public-data/poi-images/poi-f844255d-9beeb979-thumb.webp": require("../../assets/data/public-data/poi-images/poi-f844255d-9beeb979-thumb.jpg"),
  "public-data/poi-images/roman-roads-hero-89879e81-thumb.webp": require("../../assets/data/public-data/poi-images/roman-roads-hero-89879e81-thumb.jpg"),
  "public-data/poi-images/sovev-beit-hillel-start-88a84776-thumb.webp": require("../../assets/data/public-data/poi-images/sovev-beit-hillel-start-88a84776-thumb.jpg"),
  "public-data/poi-images/sovev-shear-yeshuv-start-ef0530c1-thumb.webp": require("../../assets/data/public-data/poi-images/sovev-shear-yeshuv-start-ef0530c1-thumb.jpg"),
};
