// Generated by apps/mobile/scripts/sync-offline-assets.mjs.
// Do not edit by hand. Catalog hero thumbnails for the native Discover cards,
// required from within the app package (Metro won't serve images required from
// the @cycleways/core workspace package). Keyed by the original webp logical
// path; the bundled file is a png (RN core <Image> can't decode webp on iOS).

export const ROUTE_IMAGES = {
  "public-data/poi-images/kovshey-hagolan-hero-4403bbce-thumb.webp": require("../../assets/data/public-data/poi-images/kovshey-hagolan-hero-4403bbce-thumb.png"),
  "public-data/poi-images/poi-11102fea-572cdcba-thumb.webp": require("../../assets/data/public-data/poi-images/poi-11102fea-572cdcba-thumb.png"),
  "public-data/poi-images/poi-1821461d-91d526fa-thumb.webp": require("../../assets/data/public-data/poi-images/poi-1821461d-91d526fa-thumb.png"),
  "public-data/poi-images/poi-38b469d3-eadbb56a-thumb.webp": require("../../assets/data/public-data/poi-images/poi-38b469d3-eadbb56a-thumb.png"),
  "public-data/poi-images/poi-5b6da297-fd491b50-thumb.webp": require("../../assets/data/public-data/poi-images/poi-5b6da297-fd491b50-thumb.png"),
  "public-data/poi-images/roman-roads-hero-89879e81-thumb.webp": require("../../assets/data/public-data/poi-images/roman-roads-hero-89879e81-thumb.png"),
};
