// Generated by apps/mobile/scripts/sync-offline-assets.mjs. Do not edit.
// Per-route Discover-card gallery: ordered thumbnail logical paths (resolve via
// ROUTE_IMAGES) + the set of slugs with a synced video (for the play badge).

export const ROUTE_GALLERIES = {
  "banias-gan-hatsafon": [
    "public-data/poi-images/poi-38b469d3-eadbb56a-thumb.webp",
    "public-data/poi-images/poi-1eb44fd0-4dd46f81-thumb.webp",
    "public-data/poi-images/poi-dbc2c016-6f9ee817-thumb.webp",
    "public-data/poi-images/poi-e144a450-8d7e7468-thumb.webp",
    "public-data/poi-images/poi-7442a920-eaed8fae-thumb.webp",
    "public-data/poi-images/poi-53d4e045-24f5d79e-thumb.webp",
    "public-data/poi-images/poi-77f69a67-3c7b3936-thumb.webp",
    "public-data/poi-images/poi-23d6dbf0-325f9ead-thumb.webp"
  ],
  "sovev-beit-hillel": [
    "public-data/poi-images/sovev-beit-hillel-start-88a84776-thumb.webp",
    "public-data/poi-images/poi-1a4c1f16-b96c2372-thumb.webp",
    "public-data/poi-images/poi-857aa85d-088f1532-thumb.webp",
    "public-data/poi-images/poi-d2081ac2-000a5417-thumb.webp",
    "public-data/poi-images/poi-f5fd1f27-34405fc1-thumb.webp",
    "public-data/poi-images/poi-95010070-e9f669c1-thumb.webp",
    "public-data/poi-images/poi-c723c695-dc902444-thumb.webp",
    "public-data/poi-images/poi-75f40178-b465e980-thumb.webp"
  ],
  "historic-jordan": [
    "public-data/poi-images/poi-5b6da297-fd491b50-thumb.webp",
    "public-data/poi-images/poi-c6c5fae3-e663e2e7-thumb.webp",
    "public-data/poi-images/poi-a96860fc-71a8e561-thumb.webp"
  ],
  "kovshey-hagolan": [
    "public-data/poi-images/kovshey-hagolan-hero-4403bbce-thumb.webp",
    "public-data/poi-images/poi-8e08b582-107f7255-thumb.webp",
    "public-data/poi-images/poi-972b4305-7eba303a-thumb.webp",
    "public-data/poi-images/poi-482e2483-83028d1d-thumb.webp",
    "public-data/poi-images/poi-521bbc87-9fdd2f58-thumb.webp",
    "public-data/poi-images/poi-f844255d-9beeb979-thumb.webp"
  ],
  "sovev-dafna": [
    "public-data/poi-images/poi-1821461d-91d526fa-thumb.webp",
    "public-data/poi-images/poi-2392c619-0ee99404-thumb.webp",
    "public-data/poi-images/poi-86a4607d-aeab1967-thumb.webp",
    "public-data/poi-images/poi-7f0a3972-1973492b-thumb.webp",
    "public-data/poi-images/poi-1ed71e4f-85f43b3d-thumb.webp",
    "public-data/poi-images/poi-a76cdd1b-3f8a59d2-thumb.webp",
    "public-data/poi-images/poi-0d152fab-255f43bc-thumb.webp",
    "public-data/poi-images/poi-7004abaf-b3f48c12-thumb.webp"
  ],
  "roman-roads": [
    "public-data/poi-images/roman-roads-hero-89879e81-thumb.webp",
    "public-data/poi-images/poi-521bbc87-9fdd2f58-thumb.webp",
    "public-data/poi-images/poi-8e08b582-107f7255-thumb.webp"
  ],
  "sovev-shear-yeshuv": [
    "public-data/poi-images/sovev-shear-yeshuv-start-ef0530c1-thumb.webp",
    "public-data/poi-images/poi-3af86b92-04323504-thumb.webp",
    "public-data/poi-images/poi-b0a7c0c7-d717983c-thumb.webp"
  ],
  "naftali-dishon-yosha": [
    "public-data/poi-images/poi-11102fea-572cdcba-thumb.webp",
    "public-data/poi-images/poi-03007424-8e53f5c4-thumb.webp",
    "public-data/poi-images/poi-a77bbe8c-13ec0055-thumb.webp"
  ]
};

export const ROUTE_VIDEO_SLUGS = new Set(["sovev-beit-hillel","banias-gan-hatsafon","sovev-dafna","sovev-shear-yeshuv"]);
